# █░█ █▄█ █▀█ █▀█ █░░ ▄▀█ █▄░█ █▀▄
# █▀█ ░█░ █▀▀ █▀▄ █▄▄ █▀█ █░▀█ █▄▀

$meowrch = $HOME/.config/meowrch/meowrch.py


# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/

exec-once = ~/.config/meowrch/bin/resetxdgportal.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/meowrch/bin/polkitkdeauth.sh 
exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11,ssh
exec-once = hypridle
exec-once = swww-daemon
exec-once = udiskie --no-automount --smart-tray
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 
# exec-once = python $meowrch --action set-current-theme && python $meowrch --action set-wallpaper


# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
exec-once = hyprctl setcursor Bibata-Modern-Classic 24


# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/default/autostart.conf
source = ~/.config/hypr/default/monitors.conf
source = ~/.config/hypr/default/input.conf
source = ~/.config/hypr/default/keybindings.conf
source = ~/.config/hypr/default/windowrules.conf
source = ~/.config/hypr/default/appearance.conf
source = ~/.config/hypr/default/general.conf
source = ~/.config/hypr/userprefs.conf

# Mewline
source = ~/.config/hypr/mewline.conf
