name: Build Meowrch ISO

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build ISO Image
        run: |
          # Используем nixos-generators для создания ISO из конфигурации meowrch
          nix run github:nix-community/nixos-generators -- --format iso --flake .#meowrch -o result

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meowrch-iso
          path: result/*.iso
          if-no-files-found: error
